In [4]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])

In [3]:
print(x)

[1 2 3]


In [12]:
x = [1,2,3]

In [13]:
x

[1, 2, 3]

In [9]:
y = [1,2,3]

In [10]:
y

[1, 2, 3]

In [14]:
x+y

[1, 2, 3, 1, 2, 3]

In [26]:
x = np.array([1,2,3,4,5,6,7])

In [16]:
y = np.array([1,2,3])

In [17]:
x+y

array([2, 4, 6])

In [23]:
x = np.ones((5))

In [32]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
x = np.array([[1,2,3],[1,2,3]])

In [34]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
x = np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
x = np.eye(2)

In [40]:
x

array([[1., 0.],
       [0., 1.]])

In [44]:
x = np.arange(5,10 ,2)

array([0, 1, 2, 3, 4])

In [3]:
x

NameError: name 'x' is not defined

In [6]:
x = np.array([[1, 2 , 3]]*5)

In [8]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
y = np.array([[2, 2, 2]]*5)

In [10]:
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [11]:
x+y

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [12]:
x - y

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [13]:
x/y

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [14]:
x*y

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])